### PR TITLE
Implement JWT Authentication, Signup, and Login Functionality

### PR DESCRIPTION
**Pull request by Ryadav0654**
**Title**: Implement JWT Authentication, Signup, and Login Functionality

fixes: #12 

### **Description**:
This PR introduces JWT (JSON Web Token) based authentication for securing API endpoints. The following features have been implemented:

1. **JWT Authentication Setup**:
   - JWT is now used to generate and verify authentication tokens for user sessions.
   
2. **Signup Endpoint** (`/signup`):
   - Users can now create an account by providing their details (e.g., username, email, password, etc.).
   - Passwords are securely hashed before storing in the database.
   - User data is saved in MongoDB .
   
3. **Login Endpoint** (`/login`):
   - Users can log in by providing valid credentials.
   - Upon successful authentication, a JWT token is returned, which can be used to access protected endpoints.

4. **Database Integration**:
   - MongoDB is used to persist user data.

### **Key Changes**:
- Added JWT utility for token creation and verification.
- Created models and controllers for user authentication.
- Configured MongoDB for user data storage.
- Implemented routes for signup and login.

### **Testing**:
- Manually tested the signup and login functionality.
- Verified that JWT tokens are correctly generated and validated.
- Ensured user data is stored and retrieved from the database as expected.

Screenshot 2024-10-05 225410
Screenshot 2024-10-05 225450

Let me know if you have any suggestions or feedback! Thanks!

### CODE REVIEW

**Comment by Ryadav0654** [comment]
Hi @arshadpatel ,

I have created this pull request.
Could you please review the changes when you have time? Your feedback would be appreciated!

Thanks!

**Comment by Ryadav0654** [comment]
@arshadpatel Thank you for merging the PR! I appreciate the opportunity and look forward to contributing more in the future.

**Comment by arshadpatel** [comment]
Thank You.

**Comment by Ryadav0654** [comment]
> Thank You.
Hi @arshadpatel ,
please add hactoberfest-accepted label.
Thank you!

**Pull request merged**
