### PR TITLE
footer added

### PR DESCRIPTION
**Pull request by Wasid786**
# Pull Request: Add Footer to Project

## Description
This pull request adds a footer to the project, enhancing the overall layout and user experience. The footer contains relevant information such as copyright details, links to important pages, and any necessary disclaimers.

### Changes:
- Implemented a new footer component.
- Ensured responsive design for the footer across different devices.
- Added styling to match the existing theme of the application.

## To Know
I need your social media account to add it to icons. Can you provide it?

Please review and let me know if there are any changes or further enhancements needed.

### CODE REVIEW

**Comment by arshadpatel** [comment]
Perfect! I’ve reviewed your changes, and they look great. Thank you for your attention to detail, especially with the responsiveness and matching the design theme. I’m going to merge your changes now.

I’d also appreciate it if you could take a look at the other issues in the project. Your efforts and contributions are always welcome! And if you like the project, don’t forget to give it a ⭐️ on the repo!

Thanks again for your awesome contribution!

**Comment by arshadpatel** [comment]
@Wasid786 Please do mention the issue number or issue ID which you have solved!!!

**Comment by Wasid786** [comment]
@arshadpatel  Improve Footer Design #10

**Comment by arshadpatel** [comment]
Perfect 👍

**Pull request merged**
