### PR TITLE
Enhance the Navigation Bar #1

### PR DESCRIPTION
**Pull request by hmnshi**
task done..
1. add hover effect and highlight to the links in the navbar.
2. enhancing the navbar into fully responsive navbar for the mobile-size screen.
3. change the color of div belong to main according to color-palette.

### CODE REVIEW

**Comment by arshadpatel** [comment]
Thank you, @hmnshi, for your interest in my project! I’ve reviewed your code and appreciate the changes you’ve made. I particularly liked the responsiveness of the website, as you’ve used Bootstrap effectively. However, it’s not fully aligned with the design requirements.

I would like you to revisit the code and improve the responsiveness. You can use either Bootstrap or CSS, whichever you prefer, but please ensure that the design remains consistent with the original layout. I’ll share screenshots of both the original webpage and your version for reference. The current changes differ significantly from the intended design, so I’d like you to make adjustments based on the original.

Once the updates are made, I’ll be happy to merge your pull request. Thank you for your cooperation!

Original :- 
Screenshot 2024-10-03 083126

Your version :- 
Screenshot 2024-10-03 083030

**Comment by hmnshi** [comment]
can you check my changes before make it to final.

**Comment by hmnshi** [comment]
Screenshot (420)

**Pull request closed without merging**
