### PR TITLE
Enhance Course Recommendations Section with Thumbnails and Responsive Design

### PR DESCRIPTION
**Pull request by Ryadav0654**
fixes Issue: #6 

This update enhances the course recommendations section to provide a more visually engaging and responsive layout. Key changes include:

- **Course Thumbnails**: Added course images to each recommended course card to create a more attractive and informative section.
- **Responsive Design**: Implemented a flexible layout using flexbox, ensuring the section adapts well to different screen sizes, including mobile devices.
- **Interactive Course Cards**: Introduced subtle hover effects for the course cards and buttons to improve interactivity and user experience.
- **Updated Styling**: Refined the typography and button design to maintain a clean, modern, and consistent look across the page.

### Testing
Tested the updated layout on different screen sizes to confirm that it is fully responsive. The hover effects, card layout, and images render correctly on both desktop and mobile views.

https://github.com/user-attachments/assets/ae295565-5bbd-45f2-b6a6-5ea9e9a449a5

### Additional Notes
- Placeholder images were used for course thumbnails in the implementation. These should be replaced with actual course image URLs in production.

### CODE REVIEW

**Comment by Ryadav0654** [comment]
Hi @arshadpatel  ,

I have created this pull request(#46 )
Could you please review the changes when you have time? Your feedback would be appreciated!

Thanks!

**Review by arshadpatel — APPROVED** [review]
Extremely Good

**Comment by Ryadav0654** [comment]
@arshadpatel  Thank you for merging the PR! I appreciate the opportunity and look forward to contributing more in the future.

**Comment by arshadpatel** [comment]
Thank You.

**Pull request merged**
