### PR TITLE
issue#9-fixed

### PR DESCRIPTION
**Pull request by uzefaqureshi06**

### CODE REVIEW

**Comment by uzefaqureshi06** [comment]
@arshadpatel I have raised my PR can you please review it and can you also merge it

**Review by arshadpatel — COMMENTED** [review]
@uzefaqureshi06 
I liked your design but it is not matching the theme of our project...
Let us update this issue by making a section of contact us above the footer so that contact us section is available on the main page itself... 
Whatever content you have added such as name, email, message is too good.... but design it in such a way that it matches the page theme color... 
Our Main theme:- 
Screenshot 2024-10-03 212505
Your contact page:-
Screenshot 2024-10-03 212523


I will update the issue again and assign you the issue so now you are good to go.. I respect your patience and hoping you will contribute 

Thank You

**Comment by uzefaqureshi06** [comment]
can I update this project or you want to give me next project

**Comment by arshadpatel** [comment]
You can update the contact section on the main page itself above the footer instead of creating separate contact page

**Pull request closed without merging**
