### PR TITLE
feat: Add responsive behavior with trasparent navbar background

### PR DESCRIPTION
**Pull request by munna-yadav**
This pr solves issue #7 with a responsive user interface and a navbar with transparent background where the navbar up on clicking changes to a cross bar and vice-versa
nav

### CODE REVIEW

**Review by arshadpatel — APPROVED** [review]
Perfect!!

**Comment by arshadpatel** [comment]
Hii @munna-yadav Can you fix this??

image

**Comment by munna-yadav** [comment]
@arshadpatel can you tell me what view is this? like screen width

**Comment by arshadpatel** [comment]
Please refer the code

**Pull request merged**
