### PR TITLE
feat: add course management api

### PR DESCRIPTION
**Pull request by prateek168**
This PR solves : #15 

This PR setups : 
- Endpoints to add the courses
- Modular Folder Structure 
- Update README related to the API
-  Added Morgan for logging

I have performed self test of my code and tested everything locally .
@arshadpatel Can you please review this ? And let me know if any adjustments are needed .

### Demo API Call 
s1

### CODE REVIEW

**Review by arshadpatel — COMMENTED** [review]
It looks good. I will review it and let you know if any changes are required.
Thank you, @prateek168, for your contribution.

**Comment by prateek168** [comment]
@arshadpatel Thank you for reviewing the implementation and I hope it aligns with the project requirements . Can you please let me know if there are any changes or improvements you'd suggest?

**Review by arshadpatel — COMMENTED** [review]
**Request for Changes**
Hello @prateek168 ,

I've decided to structure the codeX100 repository to include both frontend and backend under the same project while using npm for package management.

Please refer to the proposed hierarchy below and update the repository accordingly:

image

Let me know if you have any questions or need assistance with the changes!

Thank you!

**Comment by geekyharsh05** [comment]
@arshadpatel pnpm is fast and better than npm why can't we use that.

**Comment by arshadpatel** [comment]
Thank You @geekyharsh05 for your reference... We will continue with pnpm

**Comment by arshadpatel** [comment]
What is your opinion on proposed hierarchy? If you are good to go with this then please update your repository accordingly.

image

**Comment by geekyharsh05** [comment]
@arshadpatel LGTM, But the frontend is not ready for proper containerization, use react(vite) in frontend. It'll be better.

**Comment by geekyharsh05** [comment]
@arshadpatel What are your thoughts on his first pr?

**Comment by prateek168** [comment]
@arshadpatel I followed your folder structure but encountered too many conflicts. Should I continue with this?
 
final

**Comment by prateek168** [comment]
@arshadpatel I've resolved the merge conflicts & followed your folder structure. Please review the changes to ensure everything works as expected.

**Review by arshadpatel — COMMENTED** [review]
Done!!!

**Comment by prateek168** [comment]
@arshadpatel Thanks for merging! Excited to contribute more in the future.

**Comment by arshadpatel** [comment]
Thank you for your contribution! @prateek168 I'm glad to have you on board. Your work made a positive impact on the project. Looking forward to seeing more of your contributions in the future. Keep up the great work!

**Pull request merged**
